import sqlite3 as sql
from flask import Flask, render_template, request, jsonify
from flask_cors import CORS
import smtplib


def dict_factory(cursor, row):
    d = {}
    for idx, col in enumerate(cursor.description):
        d[col[0]] = row[idx]
    return d


# Open Database and creates tables registration and products
def init_sqlite_db():
    conn = sql.connect("database.db")
    conn.execute('CREATE TABLE IF NOT EXISTS registration (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, surname TEXT, email TEXT, address TEXT, suburb TEXT,  city TEXT, zipcode TEXT, password TEXT)')
    print('registration table created.')

    conn.execute('CREATE TABLE IF NOT EXISTS products (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, price TEXT, Quantity TEXT, image BLOB, description TEXT, category TEXT)')
    print('products table created.')
    conn.close()


init_sqlite_db()

app = Flask(__name__)
CORS(app)

# Adding 100 products to database
def create_product():
    with sql.connect("database.db") as conn:
        cursor = conn.cursor()
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Mens Everyday Golf Shirt - Standard Fit', 150.00, 10, 'https://i.postimg.cc/y87gsMTD/s-zoom-file.jpg', 'This stylish golf shirt is made from high-quality fabric. It looks great in most casual settings, including sporting events of various kinds.', "apparel"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Pierre Cardin Mens Polo Shirt - Grey Marl ', 700.00, 10, 'https://i.postimg.cc/4yT4wcLY/sweater2.jpg', 'Stock up your wardrobe with one of these Pierre Cardin Polo Shirts, available in a range of colours. Crafted from 100% cotton for comfort and quality, the polo features a three-button collar and the Pierre Cardin branding stitched into the chest.', "apparel"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Pierre Cardin Mens Colour Block Polo Shirt - Red/Navy', 730.00, 10, 'https://i.postimg.cc/Z56cMz50/sweater3.jpg', 'Stock your wardrobe with this Pierre Cardin Colour Block Polo Shirt, available in various colours. The design features three contrast colour blocks, in addition to the Pierre Cardin branding stitched into the chest. Made from 100% cotton, the polo has a three-button collar and is machine washable.', "apparel"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Mens Long Sleeve Elemental Golf Shirt', 300.00, 10, 'https://i.postimg.cc/Pr5bMvB3/sweater4.jpg', 'These mens long sleeves golf shirts enable you to do exactly the same. They speak your style in clear and loud terms without you having to speak for them. So, adapt these when you want to flaunt your fashion flair on the golf course and get acclaimed for it by your competitors in the game.', "apparel"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Mens Formal Shoes', 500.00, 10, 'https://i.postimg.cc/gJ4XwNkY/shoes1.jpg', 'Fashion Mens Shoes. Whats in the box ? 1 x Pair of formal shoes', "apparel"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Womens ONLY Smilla Elevated Mesh Sneaker - Light Pink', 350.00, 10, 'https://i.postimg.cc/jdqVQvxp/shoes2.jpg', 'Whats in the box? 1 x Smilla elevated mesh sneaker - light pink', "apparel"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('DC Shoes Boys Trase Casual Sneakers', 650.00, 10, 'https://i.postimg.cc/kXPFtXCG/shoes3.jpg', 'DC Shoes Boys Trase Casual Sneakers.', "apparel"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('DSL Ladies Hi Top Sneaker', 200.00, 10, 'https://i.postimg.cc/CxBhTYZC/shoes4.jpg', 'DSL Ladies Hi Top sneaker. This shoe has been created with the intention to protect your feet with great comfort and fashion to jazz up any outfit off yours.', "apparel"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Minimalist Wallet - Card Holder & Money Clip-RFID Blocking', 250.00, 10, 'https://i.postimg.cc/bNGcdgzp/wallet1.jpg', 'Organise, Protect and Select your cards easily. Forget about fumbling with fat wallets & card cases that require you to handle a stack of cards to find the one you want. Designed with RFID technology that blocks unwanted scanning devices from hacking into your credit, debit and other IDs that use RFID technology.', "apparel"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Fino Genuine Leather Wallet with Gift Box - Black', 350.00, 10, 'https://i.postimg.cc/FHj6Jnw5/wallet2.jpg', 'Genuine leather cow skin biofold wallet comes in a gift box perfect for Fathers Day, graduation, birthday gifts for Dad, or as a present for someone going to travel and it also keep your smallest everyday essentials stylishly well-organized in the Fino Leather Credit Wallet /ID Pass case.', "apparel"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Baellerry Horizon Bifold Men Wallet - Light Brown', 230.00, 10, 'https://i.postimg.cc/SQMHhsVx/wallet3.jpg', 'Baellerry Horizon Bifold Men Wallet', "apparel"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('WEAV Anti-Theft RFID Aluminium Slide Up Wallet - Silver - Silver', 200.00, 10, 'https://i.postimg.cc/QtpgfRkh/wallet4.jpg', 'RFID Theft Protection. In this growing digital world, the money in your bank is at constant risk from unwanted RFID scanners used by thieves these days. This WEAV wallet can effectively block unwanted RFID scanners as it comes with an RFID Blocking Mechanism that prevents unauthorized access to your credit/debit or even metro or ID cards.', "apparel"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Melt floral Hand Bag - Brown', 400.00, 10, 'https://i.postimg.cc/Dzcy56JR/bag1.jpg', 'Elegant Floral handbag, perfect for everyday use and on any occasion.', "apparel"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Fino Uniquely Designed Faux Leather Handbag with Purse – Black', 900.00, 10, 'https://i.postimg.cc/9XP5909N/bag2.jpg', 'This sophisticated classic carryall is just the ticket for on-the-go style.', "apparel"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Ladies Skye Hand Bag - Black', 400.00, 10, 'https://i.postimg.cc/jqc3K7PK/bag3.jpg', 'Ladies Skye Hand Bag made from a quality canvas material.', "apparel"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Melt weave Hand Bag', 300.00, 10, 'https://i.postimg.cc/NfYy8Kzy/bag4.jpg', ' Fully interlined Melt weave Hand Bag with dual shoulder handles.', "apparel"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Men Nylon Belt Military Tactical Detachable Buckle Set Of 3 Belts-Assorted', 300.00, 10, 'https://i.postimg.cc/QthLYrGq/belts1.jpg', 'Suitable for outdoor and tactical activities made from a quality nylon material.', "apparel"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Circle Stylish Black Belt', 250.00, 10, 'https://i.postimg.cc/05hThmsQ/belts2.jpg', 'Belt is 105cm long . Fits waist between 76cm and 92cm. Fits M, L, XL', "apparel"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Tactical Hunting Accessories Tactical Gear Heavy Duty Belt - Black', 230.00, 10, 'https://i.postimg.cc/DyKCqchq/belts3.jpg', 'This tactical belt is 125cm / 49in long, 3.8cm / 1.5in wide, freely adjustable and suitable for most people.', "apparel"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Marique Yssel Wrap Obi Leather Belt - Tan', 300.00, 10, 'https://i.postimg.cc/tC5zFQ2j/belts4.jpg', 'Genuine leather belt that beautifully shows off the waist. ', "apparel"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('8mm Titanium Plated Steel Ring - Black', 200.00, 10, 'https://i.postimg.cc/qq7vYKVQ/ring1.jpg', 'Main Material: Stainless Steel', "jewellery"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('925 Sterling Silver Classic Six Claw Ring', 400.00, 10, 'https://i.postimg.cc/bYKvLsV0/ring2.jpg', '925 Sterling Silver Twist Eternal Heart Swarovski Like Element Ring ', "jewellery"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Black/Silver Rhodium Zircon Ring for Women Fashion Jewelry Wedding Rings', 250.00, 10, 'https://i.postimg.cc/gjy1vSBT/ring3.jpg', 'A wonderful jewellery accessories to show your own style and make your finger more charming. Super comfortable to wear with adjustable design to fit different size fingers.', "jewellery"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Silicone Wedding Band Rings - Set of 10', 250.00, 10, 'https://i.postimg.cc/wxFVmYWd/ring4.jpg', 'Silicone Wedding Band Rings - Set of 10.', "jewellery"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Smart Watch A1 - Black', 400.00, 10, 'https://i.postimg.cc/FsH77268/watch1.jpg', 'The Smart Watch Band - A1 with its SIM card capability, this smartwatch can become a standalone watch phone that allows you to read and send texts, and make and receive calls. In case you are not using the SIM option, the smart watch can still be used to receive or make calls, and get text messages via Bluetooth 3.0 connectivity.', "jewellery"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Bad Boy Gents Analogue Watch - Leatherette Watch & Bracelet Set', 450.00, 10, 'https://i.postimg.cc/g0Wp6hJj/watch2.jpg', 'Analogue Watch with leatherette strap and bracelet.', "jewellery"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Skone Boston Chrono Mens Watch ', 750.00, 10, 'https://i.postimg.cc/4xJkfgFH/watch3.jpg', 'The powerful Boston collection is a range of military-style timepieces. This strong range is designed for the man who is always in control. Powered by a precise quartz movement, the Boston collection boasts as a functional chronograph with date display. The water-resistant casing protects your timepiece against the elements.', "jewellery"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Rose Pink Milanese Loop Steel Strap for Apple Watch - 38mm', 300.00, 10, 'https://i.postimg.cc/vB7tHpKD/watch4.jpg', 'Latest Design Milanese Loop Stainless Steel Band for your Apple Watch. ', "jewellery"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Destiny Scarlett Bracelet with Swarovski Crystals', 700.00, 10, 'https://i.postimg.cc/KvxWXyzK/bracelet1.jpg', 'The Destiny Scarlett Bracelet with Swarovski CrystalsA timeless and elegant bracelet that will add sparkle to your wrist. To help ensure that you are buying authentic crystals from Swarovski, the Swarovski seal comprises the latest security features', "jewellery"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Adjustable Silicone & Stainless Steel Bracelet', 200.00, 10, 'https://i.postimg.cc/VvGnHMvW/bracelet2.jpg', 'Silicone rubber bracelets are very popular among men, which is not surprising, given their qualities. For one, they are very comfortable and light, waterproof, and involve almost no maintenance. Aside from that, this specific item also has a stainless steel clasp. This means easy removal and the option to shorten the rubber strap, if necessary.', "jewellery"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Sterling Silver Charm Bracelet - 18cm', 300.00, 10, 'https://i.postimg.cc/FHj1Y3vC/bracelet3.jpg', 'Solid Silver charm bracelet. Charms include lock, ball, star, ladybird, key', "jewellery"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Killerdeals Anchor Charm Stainless Steel & Leather Bracelet (Unisex)', 250.00, 10, 'https://i.postimg.cc/13JX0PgD/bracelet4.jpg', 'Unisex Bracelet made up of PU Leather and Stainless steel allow. 3 Strands with Anchor Charm and spacers. 20,8 cm in length', "jewellery"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('LMA-Stud Earrings Set With Four Designs', 250.00, 10, 'https://i.postimg.cc/NfnPK2DX/earrings1.jpg', 'LMA-Stud Earrings Set With Four Designs at 8mm, packed inside a beautiful giftbox.', "jewellery"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Destiny 7 Pair Earring Set with Swarovski Crystals', 950.00, 10, 'https://i.postimg.cc/cJBmBvRX/earrings2.jpg', 'Our Destiny 7 pair earring set embellished with crystals from Swarovski will ensure you have matching earrings for every outfit. They come in a beautiful gift box and are the following colours : Aquamarine Blue, Crystal white, green garnet, Hyacinth orange, Light rose, Sapphire blue and Tanzanite purple', "jewellery"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('SilverCity Sharp Edged Hoop Earrings For Men & Women Unisex', 250.00, 10, 'https://i.postimg.cc/zBMRCNcx/earrings3.jpg', 'Hypoallergenic material - These hoop earrings are made of high-quality 316L stainless steel. Nickel-free and lead-free, resist rust and corroding. Wearing these earrings will make you more attractive and charming. These safe and comfortable earrings are suitable for women and men.', "jewellery"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('SilverCity Black Double Sided 8mm Stud Earrings For Men & Women Unisex', 250.00, 10, 'https://i.postimg.cc/yN8n1F3c/earrings4.jpg', 'Hypoallergenic material L - These stud earrings are made of high-quality 316L stainless steel. Nickel-free and lead-free, resist rust and corroding. Wearing these earrings will make you more attractive and charming. These safe and comfortable earrings are suitable for women and men.', "jewellery"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('OTC Horizontal Silver & Black Rectangle Formal Cufflinks', 250.00, 10, 'https://i.postimg.cc/ZKD5smFm/cuff1.jpg', 'Classic Style Cufflinks', "jewellery"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('OTC Personalised Alphabet Initial Letter Cufflinks - Letter X', 250.00, 10, 'https://i.postimg.cc/fbkzxr0L/cuff2.jpg', 'Add a touch of personalised elegance to your look. Premium Quality Personalised Alphabet Letter Cufflinks.', "jewellery"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('OTC Black Window Textured Frame Rectangle Cufflinks', 250.00, 10, 'https://i.postimg.cc/66fkphy1/cuff3.jpg', ' Super stylish formal Cufflinks', "jewellery"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('BodyJ4You Two Tone Classy Stylish Mens Cuff Links Style 8', 600.00, 10, 'https://i.postimg.cc/DfSxtd1X/cuff4.jpg', 'No modern man of styles accessories collection is considered complete without the addition of some sleek cufflinks, which is why we are proud to offer our cufflinks. Made out of brass and plated in a polished rhodium, these cufflinks are durable and fashionable.', "jewellery"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('LMA - 16 Pieces White Square Dinner Set', 800.00, 10, 'https://i.postimg.cc/T2cPvgGT/dine1.jpg', 'LMA - 16 Pieces White Square Dinner Set', "kitchen"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Mervyn Gers Handmade 23 Piece Dinner & Coffee Set', 5700.00, 10, 'https://i.postimg.cc/wBhpcYj9/dine2.jpg', 'This complete dinner set offers everything the family or foodie needs. From casual breakfast to elegant dinners this set combines elegance with a unique hand-made charm.', "kitchen"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('15 Piece Heavy Bottom Stainless Steel Cookware Set', 750.00, 10, 'https://i.postimg.cc/76xp3CRN/dine3.jpg', 'This 15-Piece Stainless Steel Cookware set is made of mirror polished stainless steel with a capsuled aluminum disc in the bottom.', "kitchen"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Royal Porcelain - Lustre Dinner Set - 36 Piece', 5000.00, 10, 'https://i.postimg.cc/vDRhvkBd/dine4.jpg', 'Royal Porcelain Lustre Dinner Set - 36 Piece', "kitchen"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Russell Hobbs - Apollo Digital Coffee Maker', 1050.00, 10, 'https://i.postimg.cc/0N3VQzsQ/coffee1.jpg', 'Russell Hobbs - Apollo Digital Coffee Maker. Automatic pause and Anti drip system allows serving while the machine continues to brew. Water tank with visible level indicator', "kitchen"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Russell Hobbs - 1.5 Litre Futura Filter Coffee Maker', 900.00, 10, 'https://i.postimg.cc/D07Lyh80/coffee2.jpg', 'Russell Hobbs - 1.5 Litre Futura Filter Coffee MakerThe Russell Hobbs Futura Filter Coffee Maker has an automatic pause and anti-drip system that allows serving while the machine continues to brew. There is a removable filter holder for easy cleaning.', "kitchen"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Philips - Grind and Brew Coffee Machine - Black', 2250.00, 10, 'https://i.postimg.cc/W3wqyyXv/coffee3.jpg', 'This compact Philips HD7762 grind and brew coffee machine features modern design and a unique brewing control dial so you can easily set your preferences for great tasting coffee.', "kitchen"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Nescafe Dolce Gusto - Piccolo Manual Machine', 2000.00, 10, 'https://i.postimg.cc/Ssxmytmq/coffee4.jpg', 'Compact but full of "wow" factor, the Piccolo really performs above its weight when it comes to making great coffee. Its manual lever means you can choose the amount of water you desire, allowing you to make your drink just the way you like it. Even better, its maximum 15-bar pump pressure ensures a coffee shop quality result each time, creating the attractive cream on top of your coffee', "kitchen"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Defy - C300 Water Dispenser Fridge - Silver', 5000.00, 10, 'https://i.postimg.cc/Y9CLJ3VL/fridge1.jpg', ' 226L Combi, "A+" Energy, New Slim Water Dispenser, Auto Defrost, Safety Glass Shelves, LED Interior Lighting, Satin Metallic', "kitchen"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Bosch - Series 4 Combination Fridge Freezer 324L - Silver', 9000.00, 10, 'https://i.postimg.cc/nLcvJp9L/fridge2.jpg', 'Elegant 324L fridge, wrapped in a beautiful silver colour. Dimensions : 60 x 66 x 186 cm', "kitchen"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Hisense 305L Bottom Freezer Fridge with Water Dispenser- Black Mirror', 7900.00, 10, 'https://i.postimg.cc/kgMVVwJ1/fridge3.jpg', '305L Nett Capacity, Black Mirror Finish, A+ Energy Rating, Interior LED Light, Big Freezer Box, Reversible Door, Tempered Glass Shelves, Adustable Glass Shelf, Big Bottle Rack, 3L Water Dispenser, Integrated Door Handle, 210L Nett Fridge Capacity, 95L Nett Freezer Capacity, 4 Star Freezer, Low Noise Design, Adjustable Thermostat, Adjustable Feet', "kitchen"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Miele XL freestanding fridge freezer 440L White glass front', 50000.00, 10, 'https://i.postimg.cc/mDWB923L/fridge4.jpg', 'Miele is the worlds leading manufacturer of premium domestic appliances, Elegant on the outside, spacious on the inside: new functional and convenient refrigeration.Responsibility for the future. Best performance A+++: highest efficiency and top-class freshness. ', "kitchen"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Defy - 621 Kitchenaire Solid Stove', 5000.00, 10, 'https://i.postimg.cc/W1mnV595/stove1.jpg', 'Defy - 621 Kitchenaire Solid Stove. Defy Appliances (Pty) Ltd is Southern Africas largest manufacturer and distributor of major domestic appliances. The company markets its products under the Defy brand and offers the consumer a full range of kitchen, laundry and small domestic appliances', "kitchen"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Defy-Dgs902-Multifunction Gas Electric Range Cooker', 11000.00, 10, 'https://i.postimg.cc/1tyRT38W/stove2.jpg', '5 Gas Burners-Wok Burner With Twin Flame-Electric Ignition-Flame Failure Safety Device-Multifunction Electric Oven', "kitchen"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Totai 4 Burner Gas Stove With Flame Failure Device - Black', 3900.00, 10, 'https://i.postimg.cc/dDPxHL13/stove3.jpg', 'Features & Specifications: 4 Burner Gas Stove, Flame Failure Safety Device, Gas Oven, Brass Burner Caps, Enamel Grids, Double Glass Door, Colour: Black, LPGSASA Approved, Dimensions: 495 x 545 x 800mm (W x D x H)', "kitchen"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Hisense-900mm 5 Burner Gas/Electric Stove-Stainless Steel', 12500.00, 10, 'https://i.postimg.cc/mZQJky6F/stove4.jpg', '5 Gas Burners, Cast Iron Pan Support, 1 Rapid, 2 Standard, 1 Economy, 1 Wok Burners, 1 x Small Burner - 0,90 Kw, 2 x Middle Sized Burners - 1,65 Kw, 1 x Big Burner - 2,5 Kw, 1 x Wok Burner - 4 Kw, Adjustable Feet, Flame Failure Safety Device, Auto Ignition, Splashback, Multifunction Electric Oven with Thermostat, Dual Convection Fans, 110L Nett Oven Capacity, Oven Interior Light, 6 Cooking Functions, Mechanical Timer, Dual Layer Removable Glass Door, Black Aluminium Handle, Storage Compartment, Matt Stainless Steel Finish, Uses LPG Gas, LPG Pressure: 28mbar', "kitchen"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Portable Smoothie Blender, Juicer Food Processor USB Rechargeable', 170.00, 10, 'https://i.postimg.cc/QM3W8sB7/blend1.jpg', 'Extreme Blenders presents the 2019 model of their portable blenders.More Powerful: all new blades, so much more durability, and crushing powers.Lasts Longer: Upgraded battery will last longer and perform better longer.Added bonuses: Youll love the small things that come along with your blender.', "kitchen"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Milex - Nutri1200 8-in-1 Nutritional Blender - Red', 850.00, 10, 'https://i.postimg.cc/RCWCYFG0/blend2.jpg', 'Milex - Nutri1200 8-in-1 Nutritional Blender - RedThe Nutri1200 8-in-1 Nutrition Blender helps you to make priority of your own and your familys health and well-being. Convert fresh ingredients into healthy smoothies, juices, soups, purees, dips and pates in seconds. The state of the art Super Vortex design guarantees optimal extraction of nutrients from fruits and vegetables - producing drinks and dishes that promises nothing less than pure goodness. The Nutri1200 blender from Milex has multiple mixing and blending functions that makes it a completely versatile food preparation machine. The Nutri1200 is best for making smoothies and frozen drinks since it is a specifically great blender for ice crushing and fruit and seed blending', "kitchen"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Russell Hobbs - 500W Stick Blender Set', 800.00, 10, 'https://i.postimg.cc/hty3NS2S/blend3.jpg', 'Russell Hobbs - 500W Stick Blender SetIdeally suited for making delectable sauces and soups, making home-made purées, cocktails, preparing fresh salad ingredients, salsa’s, processing of cheese and so much more', "kitchen"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Midea - 2 Litre 2200W Extreme Commercial Blender - Grey', 1850.00, 10, 'https://i.postimg.cc/CK8HJYtr/blend4.jpg', 'Midea - 2 Litre 2200W Extreme Commercial Blender - Grey. Extreme power commercial blender with 2200W and insane 30000 RPM motor. The 2 litre jug is perfect for any smoothie use', "kitchen"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('5 Light Simple Fossil White Chandelier', 900.00, 10, 'https://i.postimg.cc/GpnsLD7z/chan1.jpg', '5 Light Simple Fossil White Chandelier', "home improvement"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('The Lighting Warehouse - Chandelier Crystal Princess 10', 4050.00, 10, 'https://i.postimg.cc/3xYdzhdb/chan2.jpg', 'Chandelier Princess 10, Recommended Globes - 10 x E14 Max 5W LED (Excluded), Length - 750mm, Diameter - 800mm, Extended description -Acrylic Crystal Chandelier, Chain length - 400mm, Colour - Clear', "home improvement"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Eurolux - Erin 5 Light Chandelier', 4500.00, 10, 'https://i.postimg.cc/P55dm5Lh/chan3.jpg', 'Todays design lovers are all about showcasing individuality and personal style. Unique forms often take centre stage. Our chandeliers are perfect for almost every living space in your home. This chandelier creates the wow factor in any room. B22 max 60W Candles 230V not included.', "home improvement"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Zebbies Lighting - Bohemian - Macrame Double Volume Chandelier', 3500.00, 10, 'https://i.postimg.cc/rmX6YVpD/chan4.jpg', 'Features: 6 x E27 Globes Not Included, Off White Metal and Cotton Rope with White PVC Three Core Cable and Chain, Diameter: 550mm, Height: 960mm, Suspension: 2000mm, Suitable for Double Volume', "home improvement"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Star Master Night Light - Blue', 200.00, 10, 'https://i.postimg.cc/3J6tZLNR/light1.jpg', 'Illuminate your bedroom and marvel at the night sky indoors.This Projector rotates 360-degrees, provides a fantastic moving starry sky. It provides a calming nightlight effect', "home improvement"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('We Love Gadgets Vlogging LED Ring Light & Tripod', 300.00, 10, 'https://i.postimg.cc/q7pycnsq/light2.jpg', 'Features:, 1.1m Tripod Mount + 10 inch 26cm LED Ring Vlogging Video Light., Compact - tripod legs can be folded., Adjust the height of the tripod by adjusting the center axis., The ring light is made of 80pcs energy-saving LED beads., 3 color lighting mode adjustable brightness., Supports vertical and horizontal shooting.', "home improvement"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('12V 3528 RGB 5M LED Strip Light', 150.00, 10, 'https://i.postimg.cc/tRrL6NHS/light3.jpg', 'Super bright and stable lighting: Built-in 300 RGB LED, 60 RGB LED per meter, this RGB led strip light can provide super bright lighting.', "home improvement"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('20 LED Solar Powered LED Wall Light with Night sensor Pack 6', 350.00, 10, 'https://i.postimg.cc/G3BZkshb/light4.jpg', 'This solar-powered LED Wall Light is controlled by a light sensor + motion sensor at the same time. When people come close to the solar lamp, it will turn on automatically. When people leave after 10 seconds, the solar lamp will turn off. It is charged by the sun in the daytime and gives out light at night. No electric wires needed. Specifications: - Solar Panel: 0.55W 17% efficiency - Li-ion battery: 1200mAH: 3.7V - LED Power: 0.2W/PC 20PC - Night Sensor: Motion Angle & Distance 120 degrees 3m - Switch OFF and AUTO', "home improvement"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Digimark - Electric Fan 18 Inch - Metal - Pedestal Fan 55W', 450.00, 10, 'https://i.postimg.cc/SxZrTDD3/fan1.jpg', '18 inch (45cm) Metal Pedestal Fan, 3 Speed Settings, Oscillating Functionality, Radial Guard, Eco-friendly low electricity usage', "home improvement"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Kenwood - Floor Fan - IF450', 950.00, 10, 'https://i.postimg.cc/P5LpHydB/fan2.jpg', 'The Kenwood IF450 floor fan is the perfect addition to any home during hot weather. Its compact size allows it to sit comfortably on the floor and the useful carry handle makes it easy to move around the room. Adjust the fan speed and direction for your own personal comfort and cool down and relax in front of a Kenwood fan away from the summer sun', "home improvement"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Bennett Read Slimline Tower Fan', 800.00, 10, 'https://i.postimg.cc/fy0pZ1gV/fan3.jpg', 'SOPHISTICATED, SLIMLINE DESIGN: Enhance your living areas with the cool comfort of the Bennett Read Slimline Tower Fan. With added oscillation function, auto-off feature and remote control functionality for the ultimate uninterrupted cooling experience. MODERN SPACE-SAVING DESIGN: Elegantly designed to take up less floor area, deliver maximum cooling airflow and enhance any small office space, bedroom, living room or even kitchen! PORTABLE AND EASY TO USE: With user-friendly LED touch-control panel, convenient carry handle and lightweight design for easy portability. COMFORT AND SPEED MODES: 3 Adjustable fan speeds: Low, Mid and High. Plus 3 comfort modes: Regular, Natural and Sleep. Extended-range remote control included to adjust settings from across the room. AUTO SHUT-OFF FEATURE: Timer function with half-hour increments for unattended, energy-efficient cooling for up to 7.5 hours! OSCILLATION: Convenient oscillation function for optimal, even air-distribution with a wide coverage of up to 30m2.', "home improvement"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Rechargeable Mini Fan - Black', 150.00, 10, 'https://i.postimg.cc/zGdsCwWX/fan4.jpg', 'Compact & Portable & RechargeableHigh Wind Speed, 3 levels, Reliable Performance & Simple to Use, Easy to Recharge via USB Cable (Supplied), Standard Replaceable High Capacity Lithium-Ion Battery, Extra Torch Function, Included Items: 1x Fan, 1x Battery, 1x Cable, Output Power: 4.5W, Wind Speed at 1m : > 3m/s, Dimension (mm): 123 x 138 x 43 mm, Weight (including battery) 185g , Working Time ( per charge ) : SPEED LOW: 6 hours SPEED MEDIUM: 4 hours SPEED HIGH: 2 hours', "home improvement"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('WIFI Home Security System Alarm Wireless IP GSM System Kit', 1550.00, 10, 'https://i.postimg.cc/15b6f279/sec1.jpg', '- Built-in powerful performance CPU master based on 32-bit Cortex-M3 core. Based on uCOS - III operating system with multitasking design, providing user with a great operation experience, WIFI/GSM/GPRS network, Support APP push/SMS/voice monitoring/center monitoring etc. multi-channel alarm ways, to ensure the alarm performance stable and reliable, GPRS TCP/UDP protocol channel, compatible with multi-alarm center network protocol, convenient for network alarm, 100 defense zones for the learning of remotes and wireless detectors, 5 groups of preset alarm phone numbers and SMS numbers, Support many defense zones name such as of the gate, SOS, bedroom, window, balcony, perimeter, smoke, gas, carbon monoxide, water leaking, etc. Support many defense zone types setting such as of entry/exit zone, indoor zone, perimeter zone, 24-hour zone, etc, Support the main power failure, backup battery power shortage, tamper alarm and other extended alarm, Support external wireless siren, Support timing arm and disarm, Support for time zone settings for multi-regional area, 8 different languages optional: English, German, Russian, Spanish, Polish, Italian, French, Chinese, 20-second artificial message recording, GPRS real-time networking online, access to the latest working state at any time, Automatically alarm if offline, Center remote control, Door bell function', "home improvement"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('TP-LINK TAPO C100 Home Security Wi-Fi Camera and Alarm', 600.00, 10, 'https://i.postimg.cc/mr9GTzzL/sec2.jpg', 'Stay safe whenever and wherever you are with the smart, secure and easy Tapo C100 home security Wi-Fi Camera which comes with motion detection, sound and light alarm, night vision, 1080p crystal clear images, with up to 128GB card space and privacy mode. ', "home improvement"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('110db Built in Security Alarm Padlock', 100.00, 10, 'https://i.postimg.cc/Xv4gYtXr/sec3.jpg', 'Combines locking function with alarming function. Built-in movement triggered alarm, which can emit loud sound when the lock is hit or shaken. Adopts MCU core procedures, high-tech integrated circuit and digital sensor chip. Can be set to two states: mechanical lock and alarm.Low false alarm rate. Low power consumption. Can be used on door, window, bicycle with a Chain ( Chain not included ), container, motor bike, tricycle, pull gate, garden, etc.', "home improvement"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('4 AHD Security Recording System with Internet', 1850.00, 10, 'https://i.postimg.cc/T2gKyYSh/sec4.jpg', ' Second generation H.264 compression technology. Supports 6 different operations simultaneously; Recording, Playback, Network transmission, Backup, Mobile phone Viewing and Platform operation. Motion detection and alarm recording, with built-in domain name and remote ID. Supports IE browser, real time remote monitoring. Mobile surveillance supports: 3G smartphones, Windows Mobile, Symbian, Android, Apple(iPhone & iPad) and Blackberry. Infra-red for night viewing and 24hr full surveillance. Backups through USB and downloadable internet. VGA: Highest resolution 1280*1024 pixels. Hard drive and Monitor Not included', "home improvement"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Bedight Fancy House Rule "We Do Real" Vinyl Wall Art ', 500.00, 10, 'https://i.postimg.cc/6pgKLC4K/wall1.jpg', 'Fancy House Rule "We do real" Vinyl Wall Art', "home improvement"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('LooBrite Toilet Bowl Light Motion Activated Toilet Light Sensor LED Nightlight ', 200.00, 10, 'https://i.postimg.cc/fRGLWGKY/wall2.jpg', 'Motion Activated Toilet Nightlight (Fits ANY Toilet)', "home improvement"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Smeg - 1.7 Litre 3D Logo Kettle', 2900.00, 10, 'https://i.postimg.cc/tC1p1r7k/wall3.jpg', 'Smeg - 1.7 Litre 3D Logo Kettle. Stylish Smeg kettle available in a variety of colours - Perfect fit for any kitchen counter.', "home improvement"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Colour Splash World Map Poster', 150.00, 10, 'https://i.postimg.cc/XvtDz8nj/wall4.jpg', 'World Map - Colour Splash Poster', "home improvement"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Zanna Contemporary 3-Seater Deep Button Sofa - 220cm', 8500.00, 10, 'https://i.postimg.cc/dtXddS6V/couch1.jpg', 'Add style and elegance to your living room with this sofa by Lifestyle Home. This sofa is made of the sturdy wood frame and velvet fabric with beautiful tufting design all around. The thickly padded straight back and arms with plush foam cushioning and soft velvet upholstery adds great comfort for relaxation. By combining with the matching sofa and ottomans in our range, you can create a gorgeous look for your indoor space. ', "furniture"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('George & Mason - Luxe 3-Seater Couch & Ottoman Set With Removable Headrests - Light Grey', 9500.00, 10, 'https://i.postimg.cc/htsXsybm/couch2.jpg', 'George & Mason - Luxe 3-Seater Couch & Ottoman Set With Removable HeadrestsThis George & Mason Luxe Couch and Ottoman Set have a homely feel, fusing a contemporary and classic design, the set is covered in soft linen-like polyester. With plush seating and back support, each piece is accented with asymmetrical stitching to enhance your living space. The set comes with a matching ottoman, and the sofa itself has 2 removable headrests. A solid eucalyptus frame, wooden legs, and recycled foam makes this George & Mason Luxe Couch and ottoman set, a must-have', "furniture"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Juliette Deep Button Velvet 2-Steater Tufted Sofa - 2021 Edition', 9500.00, 10, 'https://i.postimg.cc/9FS8MbqG/couch3.jpg', 'Add style and elegance to your living room with this sofa by Lifestyle Home. This sofa is made of the sturdy wood frame and velvet fabric with beautiful tufting design all around. The thickly padded straight back and arms with plush foam cushioning and soft velvet upholstery adds great comfort for relaxation. By combining with the matching sofa and ottomans in our range, you can create a gorgeous look for your indoor space. This gorgeous piece looks stunning in a classic, transitional, modern, or chic homes. Its soft colour looks crisp and fresh, while the fabric upholstery creates an inviting look for family and guests.', "furniture"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Double Lounger Sofa Couch', 6000.00, 10, 'https://i.postimg.cc/vHRXwTRz/couch4.jpg', 'Classic Design which is luxuriously upholstered in high-quality Velvet Teal Fabric with wooden black legs to compliment this statement piece turning it into a timeless Modern Design. ', "furniture"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('ZYS 1.8m Folding Table - White', 700.00, 10, 'https://i.postimg.cc/Jn577t6k/table1.jpg', 'Easy to fold, easy to store heavy duty, stainless steel table.', "furniture"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Square Table with 4 Chairs - White', 4000.00, 10, 'https://i.postimg.cc/ZqFzp28k/table2.jpg', 'A stunning modern design, Smooth UV desktop which is easy to clean, but difficult to scratch.', "furniture"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('E-Table - Laptop Table With Usb Cooling Pad', 250.00, 10, 'https://i.postimg.cc/d0HP5dxn/table3.jpg', 'Are you a relaxed person wants to do everything on bed? But sometimes it can be difficult without a desk. How to hold a laptop? Where to put glass of water? Now everything is possible with our E-Table Portable table. It makes you comfortable to do anything at anywhere.', "furniture"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Linx IOWA Work Desk - Oak', 850.00, 10, 'https://i.postimg.cc/MpBmP83L/table4.jpg', 'Strong oak table with white legs for multiple purposes.', "furniture"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Nimtofte Premium Executive Office Chair', 1050.00, 10, 'https://i.postimg.cc/FHh0ZJcY/chair1.jpg', 'Luxurious office chair with arm rests. Padded faux leather seat and back. Roll-resistant wheels meaning chair will only move once downward pressure is applied. Height-adjustable gas lift. Butterfly mechanism. Tilt function. Self assembly required - Self-assembly required.', "furniture"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('George & Mason - Peyton Dining Chair Set - Set of 2', 1350.00, 10, 'https://i.postimg.cc/vHtVcHjb/chair2.jpg', 'George & Mason - Peyton Dining Chair Set - Set of 2Not only is the George & Mason Peyton chair sturdy to sit on, but it also has a soft cushion for added comfort. Please note that this product requires assembly. Please read the easy-to-follow assembly instructions which break it down step-by-step', "furniture"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('GT Racing Gaming Chair - Red', 3150.00, 10, 'https://i.postimg.cc/VNrvBY7S/chair3.jpg', 'Get your game on with these GT Racing gaming chairs! Comfortable cushions ensure extra comfort while gaming and the soft padding of the chair will help immerse you in your game. The modern design will complete your set up look. The lumbar support and adjustable back allows you to custom design your own comfort. The gas lift is covered by a dust cover for protection. The sturdy base and wheels allow for durability and easy movement. Coming in rage-on red or battery blasting blue, level up with these ultra gaming chairs.', "furniture"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Creative Deco Knot Cushion Stool - Plush Spandex', 550.00, 10, 'https://i.postimg.cc/3wm7xWSZ/chair4.jpg', 'Creative Deco Knot Cushion Stool – Plush Spandex', "furniture"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Postucare Limitless Base Set - 2 Comfort Levels', 4550.00, 10, 'https://i.postimg.cc/504GWtZy/bed1.jpg', 'If you’re looking for a heavy duty, comfortable, eco-friendly bed, you’ve found it! The Postucare Limitless range is unlike other beds you’ve seen before. We now live in a world where dual-purpose applications are becoming more of a necessity than a luxury, so why should you still be limited to a single comfort feeling per mattress? A very unique feature of our mattress is that one side has an extremely comfortable medium-soft feel, and the opposite bottom side of the mattress has a medium-firm feel. Essentially, we have combined the two most popular comfort levels for beds into one mattress.', "furniture"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Quality Reliable-Foam Base and Mattress Standard Length - 188cm - Single', 3450.00, 10, 'https://i.postimg.cc/kgPTd4SC/bed2.jpg', ' High-Density Foam Mattress - Standard Length Mattress including Base', "furniture"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Hazlo Gel Infused Visco Memory Foam Mattress - Single', 3600.00, 10, 'https://i.postimg.cc/Dw5pdhWK/bed3.jpg', 'Hazlo Gel Infused Visco Memory Foam Mattress', "furniture"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Jemma Metal Bed - White', 1900.00, 10, 'https://i.postimg.cc/GtJxLPG1/bed4.jpg', 'The Jenna metal bed is a single metal powder coated bed frame.', "furniture"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Kaio Corsica 1 Door Storage Cabinet', 1350.00, 10, 'https://i.postimg.cc/SNB4wQP6/cab1.jpg', 'Kaio Corsica 1 Door Storage Cabinet.', "furniture"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Play Armoire (Cupboard)', 950.00, 10, 'https://i.postimg.cc/Vsbm4bGf/cab2.jpg', 'Help favorite dolls and stuffed animals get organized with this realistic and modernly styled wooden armoire that suits any décor! There are three shelves for folded doll clothes and a rod with three hangers for dresses and jackets (clothing not included). The sturdy white closet with two hinged doors stands approximately 17 inches tall and features a wipe-clean surface. Clear instructions make it easy to assemble with just a screwdriver (not included). Mine to Love dolls and accessories encourage empathy and help kids express themselves as they explore grown-up roles and responsibilities. A childs confidence and self-esteem blossom and grow with each nurturing moment of imaginative play!', "furniture"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Kaio Perugia Display Shoe Cabinet', 1850.00, 10, 'https://i.postimg.cc/kgYpkTGk/cab3.jpg', 'Kaio Perugia Display Shoe Cabinet.', "furniture"))
        cursor.execute('INSERT INTO products(name, price, Quantity, image, description, category) VALUES (? , ? , ? , ? , ?, ?)', ('Regal Cabinet - White', 2350.00, 10, 'https://i.postimg.cc/MTSb4B7C/cab4.jpg', 'Product Specifications: 3 Shelves, 6 storage cubes', "furniture"))
        conn.commit()


create_product()


# Opens Registration Form
@app.route('https://final-database.herokuapp.com/registration/', methods=['GET'])
def enter_new_user():
    return render_template('registration.html')


# Adding User to Registration database according to user inputs
@app.route('https://final-database.herokuapp.com/add-new-record/', methods=['POST'])
def add_new_record():
    if request.method == "POST":
        msg = None
        try:
            post_data = request.get_json()
            name = post_data['name']
            surname = post_data['surname']
            email = post_data['email']
            address = post_data['address']
            suburb = post_data['suburb']
            city = post_data['city']
            zipcode = post_data['zipcode']
            password = post_data['password']

            with sql.connect('database.db') as con:
                cur = con.cursor()
                cur.execute(
                    "INSERT INTO registration (name, surname, email, address, suburb, city, zipcode, password) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
                    (name, surname, email, address, suburb, city, zipcode, password))
                con.commit()
                msg = name + " was successfully added to the database."
        except Exception as e:
            con.rollback()
            msg = "Error occurred in insert operation: " + str(e)
        finally:
            return jsonify(msg=msg)


# Displays records saved in Database
@app.route('https://final-database.herokuapp.com/show-records/', methods=["GET"])
def show_records():
    con = sql.connect("database.db")
    con.row_factory = dict_factory
    cur = con.cursor()
    cur.execute("select * from registration")
    rows = cur.fetchall()
    cur.execute("select * from products")
    product_list = cur.fetchall()
    return jsonify(rows, product_list)
    return jsonify(product_list)


# Displays single record saved in Database
@app.route('https://final-database.herokuapp.com/show-records/<int:product_id>/', methods=["GET"])
def show_record(product_id):
    con = sql.connect("database.db")
    con.row_factory = dict_factory
    cur = con.cursor()
    cur.execute("select * from products WHERE id=" + str(product_id))
    product_list = cur.fetchone()
    return jsonify(product_list)


# Deletes user from Database
@app.route('/delete-user/<int:registration_id>/', methods=["GET"])
def delete_user(registration_id):
    msg = None
    try:
        with sql.connect('database.db') as con:
            cur = con.cursor()
            cur.execute("DELETE FROM registration WHERE id=" + str(registration_id))
            con.commit()
            msg = "A record was deleted successfully from the database."
    except Exception as e:
        con.rollback()
        msg = "Error occurred when deleting a student in the database: " + str(e)
    finally:
        con.close()
        return render_template('deleted.html', msg=msg)


if __name__ == "__main__":
    app.run(debug="true")
